### ISSUE TITLE
Guests do not start after they are rebooted for first time.

### ISSUE THREAD

**Issue by tahonen** [RedHat-EMEA-SSA-Team/hetzner-ocp#1]
After first yum update for the guests server are rebooted with ansible task and then playbook waits them to be up again

```
- name: Shutdown
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for host to come back up
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 5
      timeout: 300
```
Servers are stopped, but they stay stopped. Have to run startall.yml playbook in another window to get them up and running. 

When I run setup.yml playbook again there is no restart problems.
